### ISSUE TITLE
improve security score

### ISSUE THREAD

**Issue by ThomasWaldmann** [nsupdate-info/nsupdate.info#281]
https://observatory.mozilla.org/analyze.html?host=nsupdate.info
https://securityheaders.com/?q=nsupdate.info&followRedirects=on

**Comment by elnappo** [comment]
Could you provide the current nginx configuration? Some headers like `X-XSS-Protection`, `X-Content-Type-Options`, or `HTTP Strict Transport Security` could also be added by Django itself. OWASP provides a good reference of security related headers https://www.owasp.org/index.php/OWASP_Secure_Headers_Project#X-Content-Type-Options

**Comment by ThomasWaldmann** [comment]
Stuff that can be as well solved in the application maybe better gets solved there, so everybody automatically gets it.

**Comment by elnappo** [comment]
After a deeper look at the problem I think its best to let the proxy (e.g. nginx) handle these security headers. Letting the app set these headers could lead to the following problems:

* Both the proxy and the app set the same headers. Im not sure what happens if they set the same header with different values.
* Proxy configuration gets more complicated (does not set header which Django already set). I usually only have one main configurations with is used by all sites.
* This leads to different (TLS) configurations for the app proxy and the static files as Django does not serve static files

So, I propose the following changes:
* only set security headers in dev configuration to get consistent headers across production and development environment https://github.com/nsupdate-info/nsupdate.info/compare/master...elnappo:secure-http
* add or link to a secure example configuration (nginx, apache) in the documentation

**Comment by ThomasWaldmann** [comment]
Hmm, couldn't that be confusing?

If we do it in the dev setup, will people then run the dev setup in production to get the security headers? Or will they skip configuring security headers because they were there in the dev setup?

**Comment by elnappo** [comment]
I don't think so, dev setup is for developers who hopefully know what they are doing. I added the headers in the dev configuration to make sure that problems with these headers are recognised before going into production. We should add a secure example configuration in the documentation and a link to e.g. Observatory. I could add a comment in the dev configuration to make this more clear.

**Comment by ThomasWaldmann** [comment]
I set some stuff via nginx now, observatory show "C" score now, but still some stuff to be improved.

**Comment by elnappo** [comment]
Added `Referrer-Policy` header

**Comment by ThomasWaldmann** [comment]
With went from C to B on securityheaders.com.

**Comment by elnappo** [comment]
For nsupdate.info we could also:
* Update nginx cipher suites (how much compatibly do we need?)
* Set CAA DNS Record

**Comment by elnappo** [comment]
`Expect-CT: enforce, max-age=21600`
