### ISSUE TITLE
OpenWRT ddns-scripts timer settings ?

### ISSUE THREAD

**Issue by 2SI3NX** [nsupdate-info/nsupdate.info#318]
I think it would be less confusing for some users if you could please state the correct timer settings for ddns-scripts on OpenWRT, such as in the attachment
![timer](https://user-images.githubusercontent.com/10450920/27327413-cfd19da6-55ae-11e7-867c-1fbd144191d6.jpg)

Would these settings be correct to not cause abuse?
Force interval was set to every one hour, and noticed that it caused abuse every few months or so.

**Comment by ThomasWaldmann** [comment]
Well, this updater seems a bit strange.

If this is your external router (that has your public IP), it should precisely "know" when the IP changes because this is a local event on its own internet-facing interface.
Thus, a timer-based check interval should not be needed.

So, try choosing a medium check interval, like every 30 minutes.
In case you have to wait 30 minutes then after each IP change (that means the router does not implement a "interface ip changed" event triggering a dyndns update otherwise), go back to 5 or 10 minutes.

Force interval should not be needed at all, but for us, it is good if you configure a very long force interval, like once per month. Then the service knows your host is alive even if it never changes its IP.

Error retry counter should be a low value, thus not 0 (infinite). If there is a problem that does not resolve after a "few" tries (100), someone likely has to manually fix something.

Error retry interval: I'ld use 10 minutes or so.
