### ISSUE TITLE
How to handle abuse reports

### ISSUE THREAD

**Issue by alainwolf** [nsupdate-info/nsupdate.info#473]
As a owner of a public domain on nsupdate.info, I sometimes get abuse reports from third parties regarding users who use a host-name under my domain for illicit activities.
I can delete those host records from my DNS server, but nothing is stopping the user to register it again or another one. 

What would be the proper way of handling this? Forward reports to abuse@dnsupdate.info?

**Comment by ThomasWaldmann** [comment]
You can't do anything about abusers re-registering abusive domains or fresh ones.

Although there is a blacklist of hostnames which can be used by me to avoid registering some names, they can just choose another name for their activities. Also, killing an abusive user is only little effective because they can just create a new user account.

About abuse reports: they are sometimes a bit stupid:
- re-registering issue, see above
- if the base domain is registered on the public suffix list (like nsupdate.info), it should be treated like a TLD - nobody complains to the .com registrar if a abusive domain is found.
- if one wants to get rid of illegal content on the internet, one has to kill the hosting / the ip connectivity, not a specific dns entry (which is just a pointer to that IP / hosting)

**Comment by alainwolf** [comment]
Thank you Thomas. 
I just wanted to make sure we are on the same page here, which we are. 
And that this is now documented somehow for future reference.
Have a nice day.
